# bandit:skip-file  -- SQL strings are quiz fixtures, not live queries
"""Persist iter 5-12 batches from a compact in-script representation."""
import json, pathlib
ROOT = pathlib.Path(__file__).parent / 'raw'

batches = {
5: [
    {"lang":"python","code":"def average(nums):\n    if not nums: return 0.0\n    return sum(nums) / len(nums)","question":"Why guard against empty list before division?","options":["len([]) == 0 causes ZeroDivisionError on the division","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"bug","subtopic":"empty-input","difficulty":"easy","explain":"Dividing by len([]) raises ZeroDivisionError. Guard aggregate functions against empty inputs before dividing or indexing. The defensive programming principle requires explicit handling of boundary cases.","sources":["CWE-369"]},
    {"lang":"javascript","code":"function findUser(users, id) {\n  return users.find(u => u.id === id);\n}","question":"Why === over ==?","options":["Strict equality avoids type coercion surprises","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"style","subtopic":"strict-equality","difficulty":"easy","explain":"== performs type coercion which is flagged by ESLint eqeqeq. Using block-scoped declarations and strict equality reduces hoisting surprises and coercion bugs. The review principle of explicit comparison surfaces type mismatches early.","sources":["Airbnb JS Style Guide"]},
    {"lang":"go","code":"package main\n\nimport (\n\t\"database/sql\"\n)\n\nfunc getUser(db *sql.DB, name string) (string, error) {\n\tvar email string\n\terr := db.QueryRow(\"SELECT email FROM users WHERE name = ?\", name).Scan(&email)\n\treturn email, err\n}","question":"Why parameterized query vs string formatting?","options":["Defends against SQL injection by separating data from code","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"security","subtopic":"sql-injection","difficulty":"easy","explain":"User-controlled input must never be interpolated into SQL text. Parameterized queries with placeholders let the driver handle escaping, preserving the value/code boundary. This is the canonical defense against CWE-89 injection vulnerabilities.","sources":["OWASP A03"]},
    {"lang":"rust","code":"pub fn sum_positive(nums: &[i32]) -> i32 {\n    nums.iter().filter(|&&x| x > 0).sum()\n}","question":"Why iterator combinators over an indexed loop?","options":["Slices are more general than &Vec; iterators elide bounds checks","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"style","subtopic":"slice-and-iterator","difficulty":"easy","explain":"Idiomatic Rust prefers slices over &Vec and iterator combinators over index loops. Programming to the most general borrowed type and leveraging the iterator API improves reuse and clarity while letting the optimizer prove bounds checks unnecessary.","sources":["Clippy needless_range_loop"]},
    {"lang":"sql","code":"SELECT department, AVG(salary) AS avg_sal\nFROM employees\nWHERE salary IS NOT NULL\nGROUP BY department\nHAVING AVG(salary) > 50000;","question":"Why filter NULL salaries before AVG?","options":["AVG skips NULL by default; explicit filter documents intent and excludes all-NULL groups","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"null-in-aggregate","difficulty":"med","explain":"Aggregate functions like AVG ignore NULL inputs and a customer with all-NULL salaries yields AVG = NULL which fails the predicate. Explicitly handling NULL in aggregates with COALESCE or filtering upfront makes the contract clear to readers.","sources":["PostgreSQL aggregate docs"]}
],
6: [
    {"lang":"python","code":"import sqlite3\n\ndef get_user(conn, username):\n    cur = conn.cursor()\n    cur.execute('SELECT id, email FROM users WHERE name = ?', (username,))\n    return cur.fetchone()","question":"Why parameter binding here?","options":["Defends against SQL injection by escaping at driver level","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"security","subtopic":"sql-injection","difficulty":"easy","explain":"String concatenation of untrusted input into SQL statements is a textbook injection vector. DB-API parameter substitution delegates escaping to the driver and preserves the value/code boundary, a foundational defense against CWE-89 vulnerabilities.","sources":["CWE-89"]},
    {"lang":"javascript","code":"function sumPositives(arr) {\n  let total = 0;\n  for (let i = 0; i < arr.length; i++) {\n    if (arr[i] > 0) total += arr[i];\n  }\n  return total;\n}","question":"Why i < arr.length not i <= arr.length?","options":["Indices run 0..length-1; off-by-one would read undefined","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"off-by-one","difficulty":"easy","explain":"Array indices run from 0 to length-1, so the terminating condition must be i < arr.length. Reading arr[arr.length] yields undefined which would poison the sum. The fence-post principle: the number of valid indices equals length, not length+1.","sources":["MDN Array.length"]},
    {"lang":"javascript","code":"function uniqueIds(users) {\n  const seen = new Set();\n  const out = [];\n  for (const u of users) {\n    if (!seen.has(u.id)) { seen.add(u.id); out.push(u); }\n  }\n  return out;\n}","question":"Why Set over a plain object for de-duplication?","options":["Set keys preserve identity; object keys coerce to strings and may collide with prototype keys","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"prototype-keys","difficulty":"med","explain":"A plain object inherits from Object.prototype so keys such as toString or proto are pre-populated or have special meaning, breaking membership checks and risking prototype pollution. Use Set or Map for clean lookup tables.","sources":["MDN Set vs Object"]},
    {"lang":"go","code":"package main\n\nimport \"fmt\"\n\nfunc firstEven(xs []int) (int, bool) {\n\tfor _, x := range xs {\n\t\tif x%2 == 0 {\n\t\t\treturn x, true\n\t\t}\n\t}\n\treturn 0, false\n}\n\nfunc main() { fmt.Println(firstEven([]int{1, 2, 3})) }","question":"Why return (int, bool) over a sentinel?","options":["Comma-ok pattern keeps success/failure out of the value space","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"sentinel-collision","difficulty":"easy","explain":"Using an in-band sentinel that lives inside the valid value domain conflates not-found with the legitimate result 0. The idiomatic Go remedy is the comma-ok pattern keeping signalling out of the value space.","sources":["Effective Go"]},
    {"lang":"rust","code":"pub fn build_path(parts: &[&str]) -> String {\n    let mut s = String::with_capacity(parts.iter().map(|p| p.len() + 1).sum());\n    for (i, p) in parts.iter().enumerate() {\n        if i > 0 { s.push('/'); }\n        s.push_str(p);\n    }\n    s\n}","question":"Why pre-size with capacity?","options":["Avoids repeated reallocation during push_str","Performance only","Cosmetic","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"string-prealloc","difficulty":"med","explain":"Building a string with repeated push_str may reallocate. with_capacity pre-sizes the buffer so push_str is amortized O(1). The principle of avoiding hidden quadratic work applies here.","sources":["Rust Performance Book"]}
],
7: [
    {"lang":"python","code":"def count_pairs(nums, target):\n    counts = {}\n    pairs = 0\n    for n in nums:\n        pairs += counts.get(target - n, 0)\n        counts[n] = counts.get(n, 0) + 1\n    return pairs","question":"Why one-pass hash over nested loop?","options":["O(n) with hash lookups vs O(n^2) nested scan","Performance only","Cosmetic","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"algorithmic-complexity","difficulty":"med","explain":"Counting complementary pairs can be done in linear time by walking once and looking up target-x in a hash map. This is the classic two-sum frequency principle: trade O(n) memory for O(n) time instead of O(n^2).","sources":["CLRS hashing"]},
    {"lang":"javascript","code":"function renderComment(el, comment) {\n  el.textContent = comment.author + ': ' + comment.text;\n}","question":"Why textContent over innerHTML?","options":["textContent treats input as text, preventing XSS","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"security","subtopic":"xss","difficulty":"easy","explain":"Assigning untrusted strings to innerHTML treats them as markup, so embedded scripts execute in the user origin. The safe approach is el.textContent or DOM APIs, enforcing the output-encoding-by-context principle.","sources":["OWASP XSS Cheat Sheet"]},
    {"lang":"javascript","code":"const crypto = require('crypto');\nfunction makeToken() {\n  return crypto.randomBytes(32).toString('hex');\n}","question":"Why crypto.randomBytes over Math.random?","options":["randomBytes is CSPRNG; Math.random is predictable PRNG unsuitable for tokens","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"security","subtopic":"weak-rng","difficulty":"med","explain":"Math.random is a PRNG seeded with predictable state and explicitly not for security. Tokens should use crypto.randomBytes, the CSPRNG primitive, rather than rolling from general-purpose RNG.","sources":["NIST SP 800-90A"]},
    {"lang":"go","code":"package main\n\nimport \"strings\"\n\nfunc concat(parts []string) string {\n\tvar b strings.Builder\n\tfor _, p := range parts {\n\t\tb.WriteString(p)\n\t}\n\treturn b.String()\n}","question":"Why strings.Builder over += concat?","options":["+= allocates O(n^2); Builder amortizes growth via doubling","Performance only","Cosmetic","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"string-builder","difficulty":"easy","explain":"Go strings are immutable, so s += p allocates a new backing array and copies all previously-accumulated bytes, yielding O(n^2) total memory traffic. strings.Builder amortizes growth using dynamic-array doubling.","sources":["strings.Builder docs"]},
    {"lang":"rust","code":"pub fn describe(opt: Option<String>) -> String {\n    match opt {\n        Some(v) => format!(\"got {v}\"),\n        None => String::from(\"none\"),\n    }\n}","question":"Why match over is_some + unwrap?","options":["Pattern matching binds the value in one step; is_some + unwrap duplicates the check","Cosmetic","Performance","Required syntax"],"correct_idx":0,"topic":"style","subtopic":"option-handling","difficulty":"easy","explain":"is_some followed by unwrap is a Clippy-flagged anti-pattern (unnecessary_unwrap) because it duplicates the check and loses pattern-binding ergonomics. match or if let express intent in one step using the type system instead of separate predicate-and-extract calls.","sources":["Clippy unnecessary_unwrap"]}
],
8: [
    {"lang":"python","code":"def read_lines(path):\n    result = []\n    with open(path) as f:\n        for line in f:\n            if line.startswith('ERROR'):\n                result.append(line)\n    return result","question":"Why stream file iteration vs read() then split?","options":["Iterating the file yields O(n) memory and time; loading the whole file then + concat is O(n^2)","Cosmetic","Performance only","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"streaming-vs-buffer","difficulty":"med","explain":"f.read() forces the entire file into memory and result = result + [line] allocates a new list every iteration giving O(n^2). Streaming with for line in f plus result.append is O(n) time and O(matches) memory.","sources":["CPython list amortization"]},
    {"lang":"javascript","code":"function sumNested(arr) {\n  let total = 0;\n  for (let i = 0, n = arr.length; i < n; i++) {\n    const inner = arr[i];\n    for (let j = 0, m = inner.length; j < m; j++) {\n      total += inner[j];\n    }\n  }\n  return total;\n}","question":"Why hoist arr[i] and arr[i].length into locals?","options":["Avoids repeated property reads the JIT cannot always elide","Performance only","Cosmetic","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"property-hoist","difficulty":"med","explain":"Each arr[i] and arr[i].length is a separate property access the JIT must re-resolve. Hoisting them into locals enables register allocation and skips repeated load instructions. This is loop-invariant code motion applied manually.","sources":["V8 hidden classes"]},
    {"lang":"go","code":"package main\n\nimport \"fmt\"\n\nfunc contains(m map[string]int, key string) (int, bool) {\n\tv, ok := m[key]\n\treturn v, ok\n}\n\nfunc main() { fmt.Println(contains(map[string]int{\"a\": 0}, \"a\")) }","question":"Why the comma-ok pattern?","options":["Distinguishes absence from a stored zero value","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"bug","subtopic":"zero-value-conflation","difficulty":"easy","explain":"In Go missing keys return the zero value, so a stored 0 is indistinguishable from absence using simple indexing. The idiomatic check is the comma-ok form: distinguishing zero from absent is essential for correctness.","sources":["Go spec map"]},
    {"lang":"rust","code":"use std::sync::Mutex;\nuse std::thread;\n\npub fn run() {\n    let m = Mutex::new(0);\n    thread::scope(|s| {\n        for _ in 0..4 {\n            s.spawn(|| {\n                *m.lock().unwrap() += 1;\n            });\n        }\n    });\n}","question":"Why thread::scope?","options":["Borrowed references shared with child threads are safe because scope guarantees join before drop","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"concurrency","subtopic":"scoped-threads","difficulty":"med","explain":"thread::scope lets borrowed references be shared with child threads safely because the scope guarantees they join before m is dropped. Arc is required only for static spawning; here Mutex provides the necessary acquire/release fences.","sources":["std::thread::scope"]},
    {"lang":"sql","code":"SELECT product_id, SUM(qty) AS total\nFROM order_items\nGROUP BY product_id\nHAVING SUM(qty) > 100;","question":"Why HAVING vs WHERE for the aggregate filter?","options":["WHERE runs before GROUP BY and cannot see aggregates; HAVING runs after","Cosmetic","Performance","Required syntax"],"correct_idx":0,"topic":"bug","subtopic":"where-vs-having","difficulty":"easy","explain":"WHERE is evaluated before GROUP BY, so it cannot see aggregates or their aliases. Aggregate predicates belong in HAVING, reflecting the canonical logical query processing order: FROM > WHERE > GROUP BY > HAVING > SELECT.","sources":["SQL standard"]}
],
9: [
    {"lang":"python","code":"from collections import Counter\n\ndef duplicates(items):\n    c = Counter(items)\n    return [x for x, n in c.items() if n > 1]","question":"Why Counter for duplicate detection?","options":["Counter aggregates frequencies; comprehension reports each duplicate exactly once","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"bug","subtopic":"duplicate-detection","difficulty":"med","explain":"To return each duplicate exactly once, track frequencies via collections.Counter rather than appending on every recurrence. This is the idempotent-emission principle for stream deduplication.","sources":["collections.Counter docs"]},
    {"lang":"javascript","code":"async function fetchAll(urls) {\n  return Promise.all(urls.map(u => fetch(u).then(r => r.json())));\n}","question":"Why Promise.all over for-loop with await?","options":["Independent fetches run concurrently instead of sequentially","Performance only","Cosmetic","Required syntax"],"correct_idx":0,"topic":"concurrency","subtopic":"sequential-await","difficulty":"easy","explain":"Each await suspends the loop until the current request resolves, so N requests take roughly N times latency instead of max latency. Promise.all dispatches concurrently using the structured-concurrency fan-out principle.","sources":["MDN Promise.all"]},
    {"lang":"go","code":"package main\n\nimport \"fmt\"\n\nfunc divide(a, b int) (int, error) {\n\tif b == 0 {\n\t\treturn 0, fmt.Errorf(\"divide by zero\")\n\t}\n\treturn a / b, nil\n}\n\nfunc main() { fmt.Println(divide(10, 0)) }","question":"Why the guard before division?","options":["Integer division by zero panics; guard must precede the operation","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"bug","subtopic":"guard-clause-ordering","difficulty":"easy","explain":"Integer division by zero in Go triggers a runtime panic, so a / b must never execute when b is 0. The guard clause must precede the operation it protects - the precondition-before-use principle universal to defensive programming.","sources":["Go spec integer ops"]},
    {"lang":"rust","code":"use std::sync::atomic::{AtomicUsize, Ordering};\n\nstatic COUNTER: AtomicUsize = AtomicUsize::new(0);\n\npub fn next_id() -> usize {\n    COUNTER.fetch_add(1, Ordering::Relaxed)\n}","question":"Why fetch_add vs load + store?","options":["fetch_add is atomic RMW; load+store is two ops, can interleave and lose updates","Cosmetic","Performance only","Required syntax"],"correct_idx":0,"topic":"concurrency","subtopic":"atomic-rmw","difficulty":"med","explain":"A separate load and store is not a single read-modify-write, so the increment can be lost when interleaved across threads. fetch_add performs the increment atomically, the canonical fix and a direct illustration of the RMW primitive role.","sources":["Rust atomic docs"]},
    {"lang":"sql","code":"SELECT u.id, u.name, agg.order_count, agg.total\nFROM users u\nLEFT JOIN (\n  SELECT user_id, COUNT(*) AS order_count, SUM(amount) AS total\n  FROM orders\n  GROUP BY user_id\n) agg ON agg.user_id = u.id\nWHERE u.active = TRUE\nORDER BY agg.total DESC NULLS LAST\nLIMIT 50;","question":"Why join an aggregated CTE over correlated subqueries?","options":["Single pass over orders vs N-times subquery execution","Performance only","Cosmetic","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"correlated-subquery","difficulty":"med","explain":"Each correlated scalar subquery executes per outer row, producing an N x M pattern. A single LEFT JOIN with GROUP BY scans orders just once and lets the planner use a hash or merge aggregate.","sources":["PostgreSQL query planner"]}
],
10: [
    {"lang":"python","code":"def dedupe(items):\n    seen = set()\n    out = []\n    for x in items:\n        if x not in seen:\n            seen.add(x)\n            out.append(x)\n    return out","question":"Why a set for membership over linear scan?","options":["Set is O(1) average membership; list scan is O(n) yielding O(n^2)","Performance only","Cosmetic","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"algorithmic-complexity","difficulty":"easy","explain":"Membership testing with x not in out on a list is O(n), so the loop is O(n^2). Using a set for membership reduces it to amortized O(n) by exploiting hash-based lookup.","sources":["Python time complexity"]},
    {"lang":"javascript","code":"function uniq(values) {\n  return Array.from(new Set(values));\n}","question":"Why Set over a plain object as dedupe table?","options":["Set preserves key identity; object keys coerce to strings causing collisions","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"key-coercion","difficulty":"easy","explain":"Object keys coerce to strings, so 0 and 0 (string) map to the same property. Set preserves type identity via SameValueZero semantics, eliminating the coercion footgun.","sources":["ECMA-262 Set"]},
    {"lang":"go","code":"package main\n\nimport \"fmt\"\n\nfunc firstNonEmpty(ss []string) (string, bool) {\n\tfor _, s := range ss {\n\t\tif s != \"\" {\n\t\t\treturn s, true\n\t\t}\n\t}\n\treturn \"\", false\n}\n\nfunc main() { fmt.Println(firstNonEmpty(nil)) }","question":"Why return (string, bool) here?","options":["Distinguishes no-element from found-empty, avoids zero-value conflation","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"bug","subtopic":"api-design","difficulty":"med","explain":"Ranging over a nil slice yields zero iterations, so the function may return the zero value empty string meaning either no-element or found-empty. The idiomatic fix returns (string, bool) following Go comma-ok pattern.","sources":["Effective Go"]},
    {"lang":"rust","code":"pub fn split_in_half(s: &str) -> (&str, &str) {\n    let target = s.len() / 2;\n    let mut mid = target;\n    while mid > 0 && !s.is_char_boundary(mid) { mid -= 1; }\n    s.split_at(mid)\n}","question":"Why is_char_boundary scan?","options":["Plain byte-half may land mid-codepoint; align to UTF-8 char boundary","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"utf8-boundary","difficulty":"hard","explain":"Rust str indexing is in bytes but enforces char-boundary alignment. For multi-byte strings, byte length divided by 2 may fall between bytes of a single char, panicking on slice. is_char_boundary finds a safe split point.","sources":["Rust str docs"]},
    {"lang":"sql","code":"SELECT *\nFROM events\nWHERE created_at >= '2026-05-20'\n  AND created_at <  '2026-05-21'\n  AND status = 'OK'\nORDER BY created_at DESC;","question":"Why a half-open range over DATE(created_at) = '2026-05-20'?","options":["DATE() wraps the column making it non-sargable; range form keeps the index usable","Cosmetic","Performance only","Required syntax"],"correct_idx":0,"topic":"perf","subtopic":"sargability","difficulty":"easy","explain":"Applying a function to an indexed column forces a full scan. The optimizer cannot translate function output back into an index range. Rewriting as a half-open range restores sargability.","sources":["Use The Index Luke"]}
],
11: [
    {"lang":"python","code":"def median(nums):\n    if not nums: return None\n    s = sorted(nums)\n    n = len(s)\n    mid = n // 2\n    if n % 2:\n        return s[mid]\n    return (s[mid-1] + s[mid]) / 2","question":"Why average two middle values for even-length input?","options":["Median of even-length data is the mean of the two central order statistics","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"median-even-length","difficulty":"med","explain":"The mathematical median of an even-length sample is the mean of the two central order statistics, not a single index. Returning s[n//2] biases the result upward by one position and violates the median symmetry property.","sources":["wikipedia median"]},
    {"lang":"javascript","code":"const path = require('path');\nfunction safePath(root, name) {\n  const requested = path.resolve(root, name);\n  if (!requested.startsWith(root + path.sep)) {\n    throw new Error('outside root');\n  }\n  return requested;\n}","question":"Why resolve + prefix check?","options":["Prevents path traversal via .. escape; canonicalize then verify within root","Cosmetic","Performance","Required syntax"],"correct_idx":0,"topic":"security","subtopic":"path-traversal","difficulty":"med","explain":"Concatenating untrusted input into a filesystem path lets an attacker submit dot-dot sequences and escape the intended directory. Canonicalize via path.resolve then verify the result starts with the allowed root (CWE-22).","sources":["CWE-22"]},
    {"lang":"go","code":"package main\n\nimport (\n\t\"context\"\n\t\"sync\"\n)\n\nfunc Fetch(ctx context.Context, urls []string, fetch func(string) string) []string {\n\tout := make(chan string, len(urls))\n\tvar wg sync.WaitGroup\n\tfor _, u := range urls {\n\t\twg.Add(1)\n\t\tgo func(u string) {\n\t\t\tdefer wg.Done()\n\t\t\tout <- fetch(u)\n\t\t}(u)\n\t}\n\twg.Wait()\n\tclose(out)\n\tres := []string{}\n\tfor s := range out {\n\t\tres = append(res, s)\n\t}\n\treturn res\n}","question":"Why buffer the channel to len(urls)?","options":["Prevents goroutine leak when caller returns early without draining","Cosmetic","Performance","Required syntax"],"correct_idx":0,"topic":"concurrency","subtopic":"goroutine-leak","difficulty":"hard","explain":"On early return goroutines block forever on an unbuffered channel with no receiver, leaking until process exit. Buffering to len(urls) lets them complete without a receiver waiting.","sources":["Dave Cheney never start goroutine"]},
    {"lang":"rust","code":"use std::sync::{Arc, Mutex};\n\npub struct Counter(Arc<Mutex<u64>>);\n\nimpl Counter {\n    pub fn inc(&self) {\n        let mut g = self.0.lock().unwrap();\n        *g += 1;\n    }\n}","question":"Why Arc<Mutex<u64>> rather than Arc<u64>?","options":["Arc gives shared but immutable access; Mutex adds interior mutability","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"concurrency","subtopic":"interior-mutability","difficulty":"med","explain":"Arc gives shared ownership but only immutable access to its contents, enforcing aliasing-XOR-mutability across threads. To mutate shared state safely, wrap in an atomic type or a Mutex; bare Arc<u64> is read-only.","sources":["Arc docs"]},
    {"lang":"sql","code":"SELECT id, name, email\nFROM users\nWHERE status = 'active'\n  AND created_at > '2025-01-01'\nORDER BY name;","question":"Why ORDER BY name (column reference) over ORDER BY 2 (ordinal)?","options":["Ordinal breaks silently if the SELECT list is reordered; column name is refactor-safe","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"style","subtopic":"ordinal-order-by","difficulty":"easy","explain":"Positional ORDER BY couples sort order to column position, so any later reordering of the SELECT list silently changes results. Always sort by explicit column name or alias to make intent locally readable.","sources":["sqlstyle.guide"]}
],
12: [
    {"lang":"python","code":"import hashlib, os\nfrom hashlib import pbkdf2_hmac\n\ndef hash_password(pw: str):\n    salt = os.urandom(16)\n    digest = pbkdf2_hmac('sha256', pw.encode(), salt, 100000)\n    return salt, digest","question":"Why pbkdf2_hmac with 100k iterations and 16-byte salt?","options":["Slow KDF with per-user salt resists offline cracking","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"security","subtopic":"password-hashing","difficulty":"med","explain":"Password storage requires a deliberately slow, memory-hard or iterated KDF with a unique random per-user salt of adequate length. Fast hashes like MD5 are GPU-trivial to brute force.","sources":["OWASP Password Storage"]},
    {"lang":"javascript","code":"function isAdult(user) {\n  if (typeof user?.age !== 'number') return false;\n  return user.age >= 18;\n}","question":"Why typeof number check plus optional chaining?","options":["Validates type at trust boundary; defends against null and string coercion","Performance","Cosmetic","Required syntax"],"correct_idx":0,"topic":"bug","subtopic":"type-validation","difficulty":"easy","explain":"== performs ToNumber coercion so a string 18 silently passes age check. Validate types explicitly with typeof; use optional chaining to guard against missing fields.","sources":["MDN Equality"]},
    {"lang":"go","code":"package main\n\nimport (\n\t\"context\"\n\t\"sync\"\n)\n\nfunc Sum(ctx context.Context, nums []int) int {\n\tvar mu sync.Mutex\n\ttotal := 0\n\tvar wg sync.WaitGroup\n\tfor _, n := range nums {\n\t\twg.Add(1)\n\t\tgo func(n int) {\n\t\t\tdefer wg.Done()\n\t\t\tmu.Lock()\n\t\t\ttotal += n\n\t\t\tmu.Unlock()\n\t\t}(n)\n\t}\n\twg.Wait()\n\treturn total\n}","question":"Why pass n explicitly plus use a Mutex on total?","options":["Capture-by-value avoids loop-var race; Mutex serializes total updates","Cosmetic","Performance","Required syntax"],"correct_idx":0,"topic":"concurrency","subtopic":"data-race","difficulty":"med","explain":"Pre-1.22 the loop variable is shared across iterations so goroutines may all see the last value. Passing n as parameter captures by value. Concurrent unsynchronized writes to total are also a data race the race detector flags.","sources":["Go memory model"]},
    {"lang":"rust","code":"pub fn first_char(s: &str) -> Option<char> {\n    s.chars().next()\n}","question":"Why chars().next() returning Option vs byte slice + unwrap?","options":["Byte slicing may panic on UTF-8 boundary; chars iterates codepoints safely and Option expresses empty input","Cosmetic","Performance","Required syntax"],"correct_idx":0,"topic":"edge","subtopic":"utf8-boundary","difficulty":"med","explain":"&str slicing uses byte offsets and panics if bounds are not on UTF-8 char boundaries. The idiomatic char-safe API is chars().next, returning Option to express empty input.","sources":["Rust str docs"]},
    {"lang":"sql","code":"SELECT product_id, name, price\nFROM products\nWHERE price = (\n  SELECT MAX(price) FROM products\n)\nORDER BY product_id;","question":"What style and clarity concern applies?","options":["Ties at MAX price return multiple rows; use DENSE_RANK() for explicit tie semantics","Cosmetic","Performance only","Required syntax"],"correct_idx":0,"topic":"style","subtopic":"window-vs-subquery","difficulty":"hard","explain":"The scalar subquery pattern obscures intent when ties exist. A window function like DENSE_RANK() OVER (ORDER BY price DESC) makes tie semantics explicit and lets the planner compute MAX in a single pass.","sources":["SQL window functions"]}
],
}

for n, items in batches.items():
    for it in items:
        it['iter'] = n
    p = ROOT / f"iter{n:02d}.json"
    p.write_text(json.dumps(items, ensure_ascii=False), encoding='utf-8')
    print(f"wrote {p.name} {len(items)} items")